paths:
  user_data_root: null

active_preset: weddell_test

presets:

  weddell_sea:
    hemisphere: south
    year_range: [2010, 2016]
    latitude_bounds: [-79, -62]
    longitude_bounds: [-70, -15]
    grid_resolution: 25

  full_southern_ocean:
    hemisphere: south
    year_range: [1992, 2020]
    latitude_bounds: [-80, -62]
    longitude_bounds: [-180, 180]
    grid_resolution: 25

  full_arctic:
    hemisphere: north
    year_range: [1992, 2020]
    latitude_bounds: [60, 90]
    longitude_bounds: [-180, 180]
    grid_resolution: 25

  custom_config:
    hemisphere: null # 'south' or 'north'
    year_range: [null, null] # [min_year, max_year] at least 6 years
    latitude_bounds: [null, null] # [southern, northern] max: north/south [31/90]/[-90,-40]
    longitude_bounds: [null, null] # [western, eastern] max: [-180,180]
    grid_resolution: null # Int or Float > 0.

