name: thesisrough #replace latter

channels: 
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core
  - python=3.10

  # Raw data download
  - xarray
  - cftime # decodes time units for climate forecasting netCDF convention
  - cfgrib # engine for grib xarray
  - h5netcdf # engine for NSIDC netcdf's xarray
  - h5py # engine for NSIDC netcdf's xarray
  - cdsapi # engine climate data store api library xarray


  # Computing
  - numpy
  - scipy # sparse matrix in weighted lr

  # ML Models
  - pytorch

  # Plotting
  - matplotlib
  - cartopy # map plots
  - cmocean # oceanography color maps

  # Utilities
  - tqdm # progress bars
  - requests # api request for data download
  - pyyaml # parser for yaml user configuration

